language: node_js
node_js:
 - "4"
 - "6"
services:
 - couchdb
install:
 - npm install -g standard
 - npm install
script:
 - standard -v
 - npm test
 - node examples/example.js
 - node examples/view.js
 - node examples/simple.js
 - node examples/attachment.js
 - node examples/attachment-stream.js
